---
name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - id: prevrelease
        uses: pajlada/github-action-get-latest-release@3565c30169a63b650084b700a3b9127877a15d48
        continue-on-error: true
        with:
          owner: Chatterino
          repo: pkg
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Nightly'
          asset: 'chatterino-arch-linux-x86_64.tar.gz'
