---
name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - id: prevrelease
        uses: pajlada/github-action-get-latest-release@17b1a11e1cea851caf301e5d62029585ff12dc18
        continue-on-error: true
        with:
          owner: Chatterino
          repo: pkg
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Stable'
          asset: 'chatterino-arch-linux-x86_64.tar.gz'
